# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0

    working_directory: ~/repo

    steps:
      - run: echo ${GITHUB_PERSONAL_TOKEN}
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      - run: yarn build

      - deploy:
          name: Trigger github deployment
          working_directory: ~/repo
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "cherrypie@gmail.com"
            git config user.name "Build Bot"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/giantswarm/docs.git master

